### PR TITLE
Multiple fixes for timers, timer scheduling, and related types

### PR DESCRIPTION
**Pull request by dpward**

### CODE REVIEW

**Comment by sgalgano** [comment]
Thanks for the updates.

**Comment by sgalgano** [comment]
What was the rationale for changing:

```C++
 using Clock = std::chrono::high_resolution_clock;
```
to:
 ```C++
 using Clock = std::chrono::system_clock;
```

in include/emane/types.h.

**Comment by dpward** [comment]
It's in the commit message for 468a781:

> Timed events in EMANE are implemented using timestamps based on
> `CLOCK_REALTIME`, the system-wide clock which measures real time
> (visit http://man7.org/linux/man-pages/man2/clock_gettime.2.html
> for more details). This can be found in `EMANE::Utils::Timer`.
> 
> As a result, `std::chrono::system_clock` should be used to obtain
> timestamps rather than `std::chrono::high_resolution_clock`. Based
> on the implementation of `std::chrono::high_resolution_clock`, not
> only may timed events fire at the wrong time, but timestamps may
> be based on an epoch that is different on each system (like when
> the system was booted). This would break existing assumptions in
> EMANE when running a distributed emulation.
> 
> The reason this has worked until now is that libstdc++ currently
> defines `std::chrono::high_resolution_clock` as a type alias for
> `std::chrono::system_clock`, so there will not be an actual effect
> from this change. However this will guarantee that the functions
> `EMANE::Clock::from_time_t()` and `EMANE::Clock::to_time_t()` are
> always defined.

**Comment by dpward** [comment]
Basically we have really been using `std::chrono::system_clock` anyway and taking advantage of the fact that `std::chrono::high_resolution_clock` is an alias to it. If the latter changed to something else it would completely break EMANE. We need to use the system clock for distributed processing and so we should be explicit about that.

**Comment by sgalgano** [comment]
Thanks. That was a good find and description.

**Pull request merged**
