### PR TITLE
Fix Makefile and packaging issues

### PR DESCRIPTION
**Pull request by dpward**
These commits resolve several issues building and installing/uninstalling EMANE, including many warnings about unresolved library symbols when building packages on Ubuntu. Several of these adjustments are guided by the Automake/libtool manual as well as the Fedora and Debian packaging guidelines, as indicated in the individual commit logs. These changes were tested under Fedora 24, RHEL 6, Ubuntu 16.04, and Ubuntu 14.04.

### CODE REVIEW

**Comment by sgalgano** [comment]
The plan is to migrate the emanesh package to multiple sub-packages with the toplevel renamed to emane and existing shell and event functionality split into respective sub-packages. This is part of a larger plan to move all event generation and event agent functionality into python and slim up the C++ code base. With that in mind, python-emanesh would be better named python-emane. 

These improvements are a great addition, but by themselves they don't fit the bug fix criteria to cause a halt/restart of regression tests. If you rework your pull with the python package rename quick enough, I'll see if I can get this merged in. There are a couple of issues outstanding from the first pass regression that will need to be addressed so your pull might be able to ride along.

We appreciate how active you are at improving emane's build and package capabilities.

**Comment by dpward** [comment]
Thanks for the feedback. The pull request is updated using python-emane as the package name. (I tested that this built correctly for me.) I also added a missing dependency on python-lxml.

**Comment by sgalgano** [comment]
The pkg_resources module is contained in python-setuptools and is used by emanesh module components to load schemas (via resource_filename) that have been packaged in the module.

There needs to be an additional dependency added to the spec for python-setuptools. It comes in automatically during dependency retrieval in newer distros but not el6. Since it is a required module, it makes sense to make it required for all distros not just el6.

For package installation testing minimal docker images are used to install all packages. The installation is tested to determine if all dependencies have been satisfied.

```
bash-4.1# emaneevent-pathloss 
/usr/bin/python: No module named pkg_resources
bash-4.1# yum install python-setuptools
bash-4.1# emaneevent-pathloss 
missing arguments
```

**Comment by dpward** [comment]
Sorry for the oversight. That dependency has been added back in and the pull request is updated.

**Comment by dpward** [comment]
In Ubuntu, the _pkg_resources_ Python module is actually provided by the [_python-pkg-resources_](http://packages.ubuntu.com/trusty/python-pkg-resources) package. The _python-setuptools_ package [depends](http://packages.ubuntu.com/trusty/python-setuptools) on it. So I adjusted the _python-emane_ package to have a runtime dependency on _python-pkg-resources_ instead.

In Fedora and Red Hat, this is not split into separate packages; the _pkg_resources_ module is contained in _python-setuptools_ package. So this is left as a runtime dependency in the RPM SPEC file, as it was before.

**Comment by sgalgano** [comment]
Can your rebase this against release/v1.0.1.

**Comment by sgalgano** [comment]
Thanks for the continued improvements.

**Pull request merged**
